name: Run Dockerfile

on:
  push:
    branches:
      - master

jobs:
  run-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: g2idocker/auth:latest
          context: .  # Specify the root directory
          file: Dockerfile  # Specify the Dockerfile location
          secrets: |
            "BASE64_PRIVATE_KEY=${{ secrets.BASE64_PRIVATE_KEY}}"
