name: Publish to AUR

on:
  push:
    branches:
      - master  # Trigger on any commit to the master branch

env:
  AUR_SSH_PRIVATE_KEY: ${{ secrets.MY_SECRET }}

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y git build-essential

      - name: Configure SSH and clone AUR repository
        run: |
          mkdir -p ~/.ssh
          if [ ! -f ~/.ssh/arch-torification ]; then
              echo "${{ env.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/arch-torification
              chmod 600 ~/.ssh/arch-torification
          fi

          eval "$(ssh-agent -s)"
          cat ~/.ssh/arch-torification
          ssh-add ~/.ssh/arch-torification
          mkdir -p test
          cd test
          git clone ssh://aur@aur.archlinux.org/arch-torification.git

      - name: Copy PKGBUILD and generate .SRCINFO
        run: |
          cp PKGBUILD test/arch-torification/
          cd test/arch-torification
          makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push changes to AUR
        run: |
          cd test/arch-torification
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD for version ${{ github.event.release.tag_name }}"
          git push

      - name: Clean up
        run: rm -rf test
