name: Publish to AUR

on:
  push:
    branches:
      - master  # This will trigger the action for any commit to the master branch

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y git build-essential

      - name: Print environment variables (debug)
        run: printenv

      - name: Print the AUR_SSH_PRIVATE_KEY (debug)
        run: echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}"

      - name: Configure SSH and clone AUR repository
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/arch-torification
          chmod 600 ~/.ssh/arch-torification
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/arch-torification
          mkdir -p test
          cd test
          ssh-keyscan -t rsa aur.archlinux.org >> ~/.ssh/known_hosts
          git clone ssh://aur@aur.archlinux.org/arch-torification.git

      - name: Copy PKGBUILD and generate .SRCINFO
        run: |
          cp PKGBUILD test/arch-torification/
          cd test/arch-torification
          makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push changes to AUR
        run: |
          cd test/arch-torification
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD for version ${{ github.event.release.tag_name }}"
          git push

      - name: Clean up
        run: rm -rf test
