name: Pkgbuild Updater

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENCRYPTED_PUBLIC_KEY_BASE64: ${{ secrets.ENCRYPTED_PUBLIC_KEY }}
      SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }} # Optional if you used a password to encrypt the key

    steps:
      - name: Decrypt SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$ENCRYPTED_PUBLIC_KEY_BASE64" | base64 --decode | openssl aes-256-cbc -d -out ~/.ssh/id_rsa.pub -pass pass:arch-torification -pbkdf2
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Update Pkgbuild
        run: |
          docker pull archlinux
          docker run archlinux sh -c '
            pacman --noconfirm -Syu &&
            pacman --noconfirm -S base-devel git sudo wget openssh &&
            useradd -m -G wheel arch-torification &&
            if grep -q "^#.*%wheel.*ALL=(ALL:ALL).*ALL" /etc/sudoers; then
              sed -i "/^#.*%wheel.*ALL=(ALL:ALL).*ALL/s/^#//" /etc/sudoers &&
              echo "Uncommented %wheel ALL=(ALL:ALL) ALL in sudoers file."
            else
              echo "%wheel ALL=(ALL:ALL) ALL is already uncommented in sudoers file."
            fi &&
            eval "$(ssh-agent)" &&
            ssh-add ~/.ssh/id_rsa.pub
          '
