name: Pkgbuild Updater
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and run Arch Linux container
        run: |
          docker pull archlinux/base
          docker run --name arch_container -d archlinux/base tail -f /dev/null

      - name: Run commands inside Arch Linux container
        run: |
          docker exec arch_container pacman --noconfirm -Syu
          docker exec arch_container pacman --noconfirm -S base-devel
