name: Publish to AUR

on:
  push:
    branches:
      - master

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y git build-essential

      - name: Configure SSH and clone AUR repository
        run: |
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh
          fi
          if [ ! -f ~/.ssh/arch-torification ]; then
            ssh-keygen -t rsa -b 4096 -f ~/.ssh/arch-torification -P ""
          fi
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/arch-torification
          mkdir -p test
          cd test
          git clone ssh://aur@aur.archlinux.org/arch-torification.git

      - name: Copy PKGBUILD and generate .SRCINFO
        run: |
          cp PKGBUILD test/arch-torification/
          cd test/arch-torification
          makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push changes to AUR
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD for version ${{ github.event.release.tag_name }}"
          git push

      - name: Clean up
        run: rm -rf test
