name: Pkgbuild Updater

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUR_SSH_PUBLIC_KEY: ${{ secrets.AUR_SSH_PUBLIC_KEY }}

    steps:
      - name: Update Pkgbuild
        run: |
          docker pull archlinux
          docker run archlinux sh -c '
            pacman --noconfirm -Syu &&
            pacman --noconfirm -S base-devel git sudo wget openssh &&
            useradd -m -G wheel arch-torification &&
            if grep -q "^#.*%wheel.*ALL=(ALL:ALL).*ALL" /etc/sudoers; then
              sed -i "/^#.*%wheel.*ALL=(ALL:ALL).*ALL/s/^#//" /etc/sudoers &&
              echo "Uncommented %wheel ALL=(ALL:ALL) ALL in sudoers file."
            else
              echo "%wheel ALL=(ALL:ALL) ALL is already uncommented in sudoers file."
            fi &&
            eval "$(ssh-agent)" &&
            echo "$AUR_SSH_PUBLIC_KEY" | ssh-add -
            git clone ssh://aur@aur.archlinux.org/arch-torification.git
          '
