name: Pkgbuild Updater

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step to export the environment variable to a file
      - name: Export environment variable to file
        run: echo "${{ secrets.BASE64_PRIVATE_KEY }}" > /tmp/private_key_base64

      - name: Run Docker and Execute Commands
        run: |
          docker pull archlinux && \
          docker run -d --name arch-container -v /tmp/private_key_base64:/tmp/private_key_base64 archlinux bash -c '
            pacman -Syu --noconfirm && \
            pacman -Sy --noconfirm base-devel openssl wget git sudo openssh && \
            useradd -m -G wheel -s /bin/bash arch-torification && \
            if grep -q "^#.*%wheel.*ALL=(ALL:ALL).*ALL" /etc/sudoers; then \
              sed -i "/^#.*%wheel.*ALL=(ALL:ALL).*ALL/s/^#//" /etc/sudoers && \
              echo "Uncommented %wheel ALL=(ALL:ALL) ALL in sudoers file."; \
            else \
              echo "%wheel ALL=(ALL:ALL) ALL is already uncommented in sudoers file."; \
            fi && \
            export BASE64_PRIVATE_KEY=$(cat /tmp/private_key_base64) && \
            su arch-torification -c "
              mkdir -p ~/.ssh && \
              echo \"\$BASE64_PRIVATE_KEY\" | base64 --decode > ~/.ssh/jenil && \
              chmod 600 ~/.ssh/jenil && \
              echo \"SSH key created at ~/.ssh/jenil\" && \
              ls -la ~/.ssh && \
              eval \$(ssh-agent -s) && \
              ssh-add ~/.ssh/jenil && \
              ssh-add -l && \
              whoami && \
              git clone ssh://aur@aur.archlinux.org/arch-torification.git && \
              cd arch-torification && \
              sudo rm -rf * && \
              wget https://raw.githubusercontent.com/jenil1122/Arch-torification/master/PKGBUILD && \
              makepkg --printsrcinfo > .SRCINFO && \
              git add PKGBUILD .SRCINFO && \
              git commit -m \"update\" && \
              git push
            "
