name: Publish to AUR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and update AUR
        run: |
          sudo apt install -y git build-essential
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          git clone ssh://aur@aur.archlinux.org/arch-torification.git
          cd Arch-torification
          cp ../PKGBUILD 
          makepkg --printsrcinfo > .SRCINFO
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD for version ${{ github.event.release.tag_name }}"
          git push
