name: Build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Read secret and build Docker image
        run: |
          echo "::set-env name=BASE64_PRIVATE_KEY::$(cat /run/secrets/BASE64_PRIVATE_KEY)"
          docker buildx build --build-arg BASE64_PRIVATE_KEY=$BASE64_PRIVATE_KEY -t g2idocker/auth:latest .
          docker push g2idocker/auth:latest
        env:
          BASE64_PRIVATE_KEY: ${{ secrets.BASE64_PRIVATE_KEY }}
          DOCKER_CLI_EXPERIMENTAL: enabled
