name: Pkgbuild Updater

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Docker
        run: |
          docker pull archlinux
          docker run -d --name arch-container archlinux tail -f /dev/null

      - name: Decrypt SSH Key and Clone Repository
        env:
          BASE64_PRIVATE_KEY: ${{ secrets.BASE64_PRIVATE_KEY }}
        run: |
          docker exec arch-container bash -c '
            pacman -Syu --noconfirm && \
            pacman -Sy --noconfirm base-devel openssl wget git sudo openssh && \
            useradd -m -G wheel arch-torification && \
            if grep -q "^#.*%wheel.*ALL=(ALL:ALL).*ALL" /etc/sudoers; then \
              sed -i "/^#.*%wheel.*ALL=(ALL:ALL).*ALL/s/^#//" /etc/sudoers && \
              echo "Uncommented %wheel ALL=(ALL:ALL) ALL in sudoers file."; \
            else \
              echo "%wheel ALL=(ALL:ALL) ALL is already uncommented in sudoers file."; \
            fi && \
            su - arch-torification -c '
              mkdir -p ~/.ssh && 
              echo "${BASE64_PRIVATE_KEY// /}" | base64 --decode > ~/.ssh/jenil && 
              sudo chmod 600 ~/.ssh/jenil &&
              eval \$(ssh-agent) &&
              sudo ssh-add ~/.ssh/jenil &&
              whoami &&
              git clone ssh://aur@aur.archlinux.org/arch-torification.git &&
              cd arch-torification &&
              sudo rm -rf * &&
              wget https://raw.githubusercontent.com/jenil1122/Arch-torification/master/PKGBUILD &&
              makepkg --printsrcinfo > .SRCINFO &&
              git add PKGBUILD .SRCINFO &&        
              git commit -m "update" &&                                    
              git push &&
            '
        shell: /usr/bin/bash -e {0}
