name: Pkgbuild Updater

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update Pkgbuild
      run: |
        docker pull archlinux
        docker run archlinux sh -c '
          pacman --noconfirm -Syu &&
          pacman --noconfirm -S base-devel git sudo
        '
